### PR TITLE
Default type params

### PR DESCRIPTION
**Pull request by AlexHaxe**
+ support for default type parameter
+ support for self access for abstracts
+ github action

### CODE REVIEW

**Comment by Simn** [comment]
Thank you!

**Comment by AlexHaxe** [comment]
seems the github action needs a `runs-on: ubuntu-latest` in between `build` and `strategy` to actually work. I'll add that next time...

**Comment by Simn** [comment]
By the way, would it be alright with you if we moved haxeparser to the HaxeCheckstyle org? I don't want to completely drop responsibility, but at this point you're the main contributor to this anyway. I would style check PRs and such things, of course.

**Comment by AlexHaxe** [comment]
we can do that. I'll add you to the org and we can sort out permissions once it's transferred.

**Comment by Simn** [comment]
Alright, cool! I need admin access for the transfer because that requires creating a public repository in the org.

**Comment by AlexHaxe** [comment]
ok, owner role seems to have done the trick. 
Welcome to HaxeCheckstyle! :)

**Comment by Simn** [comment]
Hah, another milestone. Thanks!

**Pull request merged**
