### PR TITLE
support for KwdExtern in package and import lines

### PR DESCRIPTION
**Pull request by AlexHaxe**
https://github.com/HaxeFoundation/haxe/blob/haxe-3.2.1/parser.ml#L526
https://github.com/HaxeFoundation/haxe/blob/haxe-3.2.1/parser.ml#L665-666

### CODE REVIEW

**Comment by Simn** [comment]
Thanks!

**Comment by Simn** [comment]
@AlexHaxe: As a heads up, this PR was incomplete. I addressed the missing cases in this commit: https://github.com/Simn/haxeparser/commit/a82a2784a89874d2c4586ba211cb46caa509fc14

**Comment by AlexHaxe** [comment]
Thanks, I didn't check all extern references in the ocaml source.

When comparing your changes with the development branch I find that in exprNext the Dot case does not handle Kwd(KwdNew) and Binp(OpOr) like in ocaml.

**Comment by Simn** [comment]
OpOr doesn't matter because it's just for display debugging.

`.new` should be supported though!

**Pull request merged**
